### ISSUE TITLE
QR Codes take a very long time to be recognized

### ISSUE THREAD

**Issue by ccoenen** [kciter/qart.js#1]
I am trying to scan codes with "Barcode Scanner" ([Play Store](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=de) / [F-Droid](https://f-droid.org/repository/browse/?fdid=com.google.zxing.client.android)) on an android device. I can't scan the provided QR-Code. Might either be the example, or the processing in general.

**Comment by ccoenen** [comment]
Turns out it _can_ be scanned, but it takes a lot longer to get the app to scan the code. Usually the recognition is instantly. With this code, I need to get wait a 3-10 seconds before it really locks on.

Is there a way to dial back the effect? I.e. make the smaller boxes "not as small"?

**Comment by kciter** [comment]
I will try to find a solution asap.

**Comment by kciter** [comment]
I think it is because of the threshold filter. I will fix it.

**Comment by rohmanhm** [comment]
I've found the same problem with `MIUI 8 Scanner`.

**Comment by kciter** [comment]
I found a solution. The QR code corner rectangle was not correctly recognized when using a dark photo. So I put a white border around the rectangle for recognition.
😄

**Comment by rohmanhm** [comment]
Using an image with color is better than the Threshold image.

**Comment by nekromoff** [comment]
Works OK now with Barcode Scanner app on Android both for color and b/w version

**Comment by imlinus** [comment]
Really nice job! Much appreciated :)

**Comment by ccoenen** [comment]
It appears to work better now. I'm marking this as closed.
