### ISSUE TITLE
size option doesn't works

### ISSUE THREAD

**Issue by superman66** [kciter/qart.js#20]
hey @kciter 
I found qartjs download from npmjs wasn't latest when I want to update vue-qart directive for the size option.
I can not find size option in source code.

**Comment by misteral** [comment]
@kciter Hi, please publish last changes to npm.

**Comment by wannymiarelli** [comment]
Yes, same here, size opt is not working

**Comment by wannymiarelli** [comment]
+1

**Comment by ChenGogo** [comment]
size option doesn't works, the value of the canvas'width is always 195, why ?

**Comment by misteral** [comment]
@ChenGogo please use the lib from github

`npm install --save kciter/qart.js`

**Comment by kciter** [comment]
1.1.2 published.
