### ISSUE TITLE
请问可以只要一个普普通通的二维码吗？

### ISSUE THREAD

**Issue by luoyali** [kciter/qart.js#25]
我这边的需求很简单，就是只需要一个普通的二维码，不需要用普通的二维码和照片合成，就只是一张普通的二维码，请问该怎么修改您提供的配置参数呢？

**Comment by skatpgusskat** [comment]
At least, write your question in English please...

**Comment by kciter** [comment]
I don't know Chinese.

**Comment by luoyali** [comment]
Well, I've solved this problem. Thank you.
