### ISSUE TITLE
Doesn't work with cyrillic text

### ISSUE THREAD

**Issue by vitalyavolyn** [kciter/qart.js#26]
When i enter text in Russian (e.g. "Привет") on https://kciter.github.io/qart.js/ , QR code that was shown (both normal and qart) decodes in  "?@825B"

I guess qart doesn't support Unicode? :thinking:

**Comment by misteral** [comment]
@vitalyavolyn hi, it work with Unicode text and it work with emoji. Master branch from GitHub as example  ![Alt text](https://monosnap.com/image/sngXNtu0u1stky76mTZeqzCMz6lrDi.png)

Close issue if all ok.
