### ISSUE TITLE
qart as a React component

### ISSUE THREAD

**Issue by hwclass** [kciter/qart.js#3]
Hi all

Sorry for my missing information about the library but the job you have done looks pretty nice. I have just wondered that you have a plan to develop this library as a React component as well?

Thanks

Baris

**Comment by kciter** [comment]
Hello, @hwclass.
I don't have a plan now. :)
But if you want to use this library in React, you can wrapped this library like [react-barcode](https://github.com/kciter/react-barcode/blob/master/src/react-barcode.js).

**Comment by BatuhanK** [comment]
@kciter @hwclass Here is a jumpstart: https://github.com/BatuhanK/react-qart

**Comment by kciter** [comment]
@BatuhanK Thank you!

**Comment by hwclass** [comment]
thanks @BatuhanK, checked the repo and congrats to you ;)
