### ISSUE TITLE
How to resize the size of qart

### ISSUE THREAD

**Issue by liupishui** [kciter/qart.js#9]
#Now the size of qart is 195px*195px,I want to resize to 200px*200px

**Comment by kciter** [comment]
This library doesn't support resize now. 😢  The resize feature is in ToDo and I will implement it.

**Comment by kciter** [comment]
If you are in a hurry, download image and resizing with image processing tool like Photoshop.

**Comment by kciter** [comment]
You can use to `version` option for resize. But, it's not an exact size.

**Comment by misteral** [comment]
Resize via image processing tool not work for me(tryed to scale 350x350).

**Comment by misteral** [comment]
@kciter Added #17
